import { describe, expect, it } from 'vitest';
import { buildTurns, currentTurn, isRealTurn, rankTurns, stepTurn, turnSummary } from './turns';

describe('turnSummary', () => {
  it('取首个非空行并压掉连续空白', () => {
    expect(turnSummary('\n\n  修一下   看板   \n第二行\n')).toBe('修一下 看板');
  });
  it('全空白输入退化为空串', () => {
    expect(turnSummary('  \n \n')).toBe('');
  });
});

describe('buildTurns', () => {
  const turns = buildTurns(
    [{ text: '最早那条', ts: 1 }, { text: '第二条' }],
    [{ text: '已装载的\n多行', ts: 3 }],
  );
  it('未装载的排在前面,序号全局连续', () => {
    expect(turns.map((t) => t.ord)).toEqual([0, 1, 2]);
    expect(turns.map((t) => t.loaded)).toEqual([false, false, true]);
  });
  it('摘要取首行,全文保留给搜索', () => {
    expect(turns[2]!.summary).toBe('已装载的');
    expect(turns[2]!.text).toBe('已装载的\n多行');
  });
});

describe('currentTurn', () => {
  const boxes = [
    { ord: 0, top: 0, bottom: 60 },
    { ord: 1, top: 200, bottom: 260 },
    { ord: 2, top: 500, bottom: 560 },
  ];
  const BAND = 36;
  const ACTIVE = 48;
  it('取最后一条起点已进入阅读区顶部的轮次', () => {
    expect(currentTurn(boxes, 300, ACTIVE, BAND)?.ord).toBe(1);
  });
  it('提问还看得见时不请出吸顶头', () => {
    expect(currentTurn(boxes, 180, ACTIVE, BAND)).toEqual({ ord: 1, gone: false });
  });
  it('提问被吸顶带盖住后才 gone', () => {
    expect(currentTurn(boxes, 260, ACTIVE, BAND)).toEqual({ ord: 1, gone: true });
  });
  // 回归:跳转把落点停在头带下方 8px,若判定阈值只到头带底,这一轮就不算当前轮,
  // ⌥↑ 会从它的上一轮起步、一按跳两轮(2026-09-02 浏览器实测抓到)
  it('刚跳到的那一轮算当前轮,而不是它的上一轮', () => {
    const landed = 200 - BAND - 8; // scrollToTurn 的落点公式
    expect(currentTurn(boxes, landed, ACTIVE, BAND)?.ord).toBe(1);
    expect(currentTurn(boxes, landed, BAND, BAND)?.ord).toBe(0); // 修复前的行为,留作对照
  });
  it('滚在第一条之前没有当前轮', () => {
    expect(currentTurn(boxes, -100, ACTIVE, BAND)).toBeNull();
    expect(currentTurn([], 0, ACTIVE, BAND)).toBeNull();
  });
});

describe('stepTurn', () => {
  it('到头即停,不回绕', () => {
    expect(stepTurn(0, -1, 3)).toBeNull();
    expect(stepTurn(2, 1, 3)).toBeNull();
    expect(stepTurn(1, 1, 3)).toBe(2);
    expect(stepTurn(1, -1, 3)).toBe(0);
  });
  it('尚无当前轮时,↑ 落最后一轮、↓ 落第一轮', () => {
    expect(stepTurn(null, -1, 3)).toBe(2);
    expect(stepTurn(null, 1, 3)).toBe(0);
  });
  it('零轮会话返回 null', () => {
    expect(stepTurn(null, 1, 0)).toBeNull();
  });
});

describe('rankTurns', () => {
  const turns = buildTurns([], [
    { text: '起验收环境' },
    { text: '开壁纸看了下,chip 底下有条横带' },
    { text: '跑质量门\n顺便确认壁纸三档都量过' },
  ]);
  it('空查询保持时间顺序', () => {
    expect(rankTurns(turns, '  ').map((t) => t.ord)).toEqual([0, 1, 2]);
  });
  it('首行命中排在正文命中之前', () => {
    expect(rankTurns(turns, '壁纸').map((t) => t.ord)).toEqual([1, 2]);
  });
  it('无命中返回空', () => {
    expect(rankTurns(turns, 'zzz')).toEqual([]);
  });
});

describe('isRealTurn', () => {
  // 取样自 5 个真实会话的转录(2026-09-02),五类元条目各自跨会话出现
  it.each([
    ['<command-name>/model</command-name>\n<command-message>model</command-message>'],
    ['<local-command-stdout>Set model to claude-opus-5[1m]</local-command-stdout>'],
    ['<local-command-caveat>Caveat: The messages below were generated by the user</local-command-caveat>'],
    ['<task-notification>\n<task-id>a130858532a1fbd18</task-id>'],
    ['[Request interrupted by user]'],
    ['[Request interrupted by user for tool use]'],
    ['   '],
  ])('元条目不算一轮:%s', (text) => {
    expect(isRealTurn(text)).toBe(false);
  });

  it('真的以尖括号开头的提问不被误伤', () => {
    expect(isRealTurn('<div class="brand"> 这段 HTML 为什么把整页搞成 flex 了?')).toBe(true);
    expect(isRealTurn('<商务需求> 帮我看下这个')).toBe(true);
  });

  it('普通提问照常算一轮', () => {
    expect(isRealTurn('把看板按项目过滤一下')).toBe(true);
  });
});

describe('buildTurns 过滤元条目', () => {
  it('元条目不占编号,序号只数真轮次', () => {
    const turns = buildTurns(
      [{ text: '<command-name>/model</command-name>' }, { text: '第一个真问题' }],
      [{ text: '[Request interrupted by user]' }, { text: '第二个真问题' }],
    );
    expect(turns.map((t) => t.summary)).toEqual(['第一个真问题', '第二个真问题']);
    expect(turns.map((t) => t.ord)).toEqual([0, 1]);
    expect(turns.map((t) => t.loaded)).toEqual([false, true]);
  });
});
